### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JianAtSeer** [anfoss/PCprophet#10]
**Describe the bug**
I installed PCprophet and try to test run it using the example command line:
python main.py -sid test/test_ids.txt -is_ppi False -db coreComplexes.txt

but the errors:
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    main()
  File "main.py", line 222, in main
    [preprocessing(infile, config) for infile in files]
  File "main.py", line 222, in <listcomp>
    [preprocessing(infile, config) for infile in files]
  File "main.py", line 208, in preprocessing
    config['GLOBAL']['mult']
  File "/home/ubuntu/Codbase/PCprophet/PCprophet/generate_features_v2.py", line 429, in runner
    feat, pks = mp_cmplx(filename=cmplx_comb, goobj=go_tree, gaf=gaf, mult=mult)
  File "/home/ubuntu/Codbase/PCprophet/PCprophet/generate_features_v2.py", line 388, in mp_cmplx
    df = pd.read_csv(filename, sep="\t")
  File "/home/ubuntu/anaconda3/envs/jian_PCProphet/lib/python3.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/ubuntu/anaconda3/envs/jian_PCProphet/lib/python3.7/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ubuntu/anaconda3/envs/jian_PCProphet/lib/python3.7/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home/ubuntu/anaconda3/envs/jian_PCProphet/lib/python3.7/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/ubuntu/anaconda3/envs/jian_PCProphet/lib/python3.7/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'./tmp/test_frac/cmplx_combined.txt' does not exist

**Extract of sample ids file and protein matrix used**
Provide example of sample_ids.txt and a sample of the input matrix used.

**To Reproduce**
python main.py -sid test/test_ids.txt -is_ppi False -db coreComplexes.txt

**Screenshots**
Provide screenshot of the terminal error message

**Desktop (please complete the following information):**
 - LInux
 - Python 3.7

**Additional context**

**Comment by anfoss** [comment]
I pushed the wrong main.py. Try with the new current commit. Otherwise you can uncomment everything between line 188 to 199  in main.py (preprocessing function)

**Comment by JianAtSeer** [comment]
Thanks for the fix.  I try to run the command line again, but I still got the same error.

python main.py -sid test/test_ids.txt -is_ppi False -db coreComplexes.txt 
mapping /home/ubuntu/Codbase/PCprophet/test/test_frac.txt to coreComplexes.txt
Generating hypothesis for /home/ubuntu/Codbase/PCprophet/test/test_frac.txt
Traceback (most recent call last):
  File "main.py", line 247, in <module>
    main()
  File "main.py", line 221, in main
    [preprocessing(infile, config) for infile in files]
  File "main.py", line 221, in <listcomp>
    [preprocessing(infile, config) for infile in files]
  File "main.py", line 207, in preprocessing
    config['GLOBAL']['mult']
  File "/home/ubuntu/Codbase/PCprophet/PCprophet/generate_features_v2.py", line 429, in runner
    feat, pks = mp_cmplx(filename=cmplx_comb, goobj=go_tree, gaf=gaf, mult=mult)
  File "/home/ubuntu/Codbase/PCprophet/PCprophet/generate_features_v2.py", line 388, in mp_cmplx
    df = pd.read_csv(filename, sep="\t")
  File "/home/ubuntu/anaconda3/envs/jian_PCProphet/lib/python3.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/ubuntu/anaconda3/envs/jian_PCProphet/lib/python3.7/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ubuntu/anaconda3/envs/jian_PCProphet/lib/python3.7/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home/ubuntu/anaconda3/envs/jian_PCProphet/lib/python3.7/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/ubuntu/anaconda3/envs/jian_PCProphet/lib/python3.7/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'./tmp/test_frac/cmplx_combined.txt' does not exist

**Comment by anfoss** [comment]
Fixed, forgot to uncomment one final line

**Comment by JianAtSeer** [comment]
Thanks for always so quick to response. But now i got a different error:
python main.py -sid test/test_ids.txt -is_ppi False -db coreComplexes.txt  -output ./ 
mapping /home/ubuntu/Codbase/PCprophet_archived/test/test_frac.txt to coreComplexes.txt
Generating hypothesis for /home/ubuntu/Codbase/PCprophet_archived/test/test_frac.txt
combining hypothesis and corum for ./tmp/test_frac
calculating features for ./tmp/test_frac/cmplx_combined.txt
Traceback (most recent call last):
  File "main.py", line 247, in <module>
    main()
  File "main.py", line 221, in main
    [preprocessing(infile, config) for infile in files]
  File "main.py", line 221, in <listcomp>
    [preprocessing(infile, config) for infile in files]
  File "main.py", line 207, in preprocessing
    config['GLOBAL']['mult']
  File "/home/ubuntu/Codbase/PCprophet_archived/PCprophet/generate_features_v2.py", line 429, in runner
    feat, pks = mp_cmplx(filename=cmplx_comb, goobj=go_tree, gaf=gaf, mult=mult)
  File "/home/ubuntu/Codbase/PCprophet_archived/PCprophet/generate_features_v2.py", line 412, in mp_cmplx
    pks = pks.apply(pd.Series.explode).reset_index()
AttributeError: type object 'Series' has no attribute 'explode'

**Comment by anfoss** [comment]
On my system works. I guess your Pandas is not updated. Update to 1.2.4

**Comment by JianAtSeer** [comment]
Thanks. I updated pandas and it works.
