### ISSUE TITLE
[BUG] Crash in predict.py from working directory assumption

### ISSUE THREAD

**Issue by s-andrews** [anfoss/PCprophet#6]
**Describe the bug**
PCProphet crashes because it can't find the default model specified in the ```runner``` method of ```predict.py```

**Extract of sample ids file and protein matrix used**
Anything where you don't specify a custom model.

**Screenshots**
```
mapping /bi/group/samant/HSP90data_PCprophet/Input/Ctrl_1.txt to coreComplexes.txt
Generating hypothesis for /bi/group/samant/HSP90data_PCprophet/Input/Ctrl_1.txt
combining hypothesis and corum for ./tmp/Ctrl_1
calculating features for ./tmp/Ctrl_1/cmplx_combined.txt
Traceback (most recent call last):
  File "/bi/apps/pcprophet/1.1/PCprophet/pcprophet", line 247, in <module>
    main()
  File "/bi/apps/pcprophet/1.1/PCprophet/pcprophet", line 221, in main
    [preprocessing(infile, config) for infile in files]
  File "/bi/apps/pcprophet/1.1/PCprophet/pcprophet", line 221, in <listcomp>
    [preprocessing(infile, config) for infile in files]
  File "/bi/apps/pcprophet/1.1/PCprophet/pcprophet", line 204, in preprocessing
    predict.runner(tmp_folder)
  File "/bi/apps/pcprophet/1.1/PCprophet/PCprophet/predict.py", line 36, in runner
    clf = deserialize(model)
  File "/bi/apps/pcprophet/1.1/PCprophet/PCprophet/predict.py", line 18, in deserialize
    clf = joblib.load(model)
  File "/bi/apps/pcprophet/1.1/packages/joblib/numpy_pickle.py", line 577, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './PCprophet/rf_allneg.clf'
```

**Comment by s-andrews** [comment]
I fixed this using the code below as the signature for the runner method.

```
def runner(base, model=None):
    """
    get model file and run prediction
    """

    if model is None:
        model = os.path.join(os.path.dirname(os.path.realpath(__file__)),"rf_allneg.clf")
```

**Comment by anfoss** [comment]
Thanks for spotting this. Will push a change right away
